name: cicd_prod

on:
  push:
    branches:
      - master
      - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/conver-flow:prod
  SEC_FILE_NAME: edcwsxqaz

jobs:
  publish:
    name: Publish Docker Image (Prod)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Convert Image Name to Lowercase
        id: string
        uses: ASzc/change-string-case-action@v5
        with:
          string: ${{ env.IMAGE_NAME }}

      - name: Update Environment Variables
        run: echo "IMAGE_NAME=${{ steps.string.outputs.lowercase }}" >> $GITHUB_ENV

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.PAT }}" | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build and Push Docker Image
        run: |
          docker build . --tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          docker push ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

  deploy:
    name: Deploy Image (Prod)
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH Keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

      - name: Create Remote Secret File
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.WORK_DIR }} && \
            touch ${{ env.SEC_FILE_NAME }} && \
            echo '${{ secrets.SEC }}' > ${{ env.SEC_FILE_NAME }}"

      - name: Deploy New Version
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo '${{ secrets.PAT }}' | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.WORK_DIR }} && \
            docker stop conver-flow-server-prod || true && \
            docker rm conver-flow-server-prod || true && \
            docker compose pull conver-flow-server-prod && \
            docker compose up -d conver-flow-server-prod"

      - name: Clean Up Remote Secret
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "\
            cd ${{ secrets.WORK_DIR }} && \
            rm -f ${{ env.SEC_FILE_NAME }}"

      - name: Cleanup SSH Keys
        run: rm -rf ~/.ssh
